### ISSUE TITLE
Hugoを他の静的サイトジェネレーターにリプレースする

### ISSUE THREAD

**Issue by masuP9** [openameba/a11y-guidelines#146]
## リプレースしたい理由

- Hugo のみ package.json で完結できていない
  - renovate によるバージョン管理の恩恵を受けることができない
  - 環境構築を単純化したい

## リプレース候補

- [11ty](https://www.11ty.dev/)
- [Gatsby](https://www.gatsbyjs.com/)
- [Next.js](https://nextjs.org)

etc...

個人的にはシンプルでスタイルやテンプレートの作り直しが少なそうな 11ty が良さそう

**Comment by peaceiris** [comment]
> * Hugo のみ package.json で完結できていない

これは Hugo 本体のことでしょうか？ [fenneclab/hugo-bin: Binary wrapper for Hugo](https://github.com/fenneclab/hugo-bin#readme) は検討されましたか？

**Comment by masuP9** [comment]
@peaceiris Hugo自体のことでした。
おお、ラッパー用のpackageがあるんですね。知りませんでした、ありがとうございます！見てみますね。
