### ISSUE TITLE
独自ドメインをあてる

### ISSUE THREAD

**Issue by herablog** [openameba/a11y-guidelines#148]
[GitHub Pagesのカスタムドメイン](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-custom-domains-and-github-pages)として 独自ドメイン (`a11y-guidelines.ameba.design`を予定)をあてる。 #146 で大きな変更が入るのでその後に対応。その際には以下の対応も同時に行う。

- [x] [ローカルでのディレクトリ再現処理](https://github.com/openameba/a11y-guidelines/pull/147#discussion_r551093651)を削除
- [x] [WebBundle生成時](https://github.com/openameba/a11y-guidelines/blob/b5b00ca29893bf419e5fabaedef3e1779a96ee88/.github/workflows/publish-webbundle.yml#L54-L60)のプライマリURLの変更

**Comment by herablog** [comment]
:congratulations:  https://a11y-guidelines.ameba.design/

**Comment by sasaplus1** [comment]
:eyes:

**Comment by tokimari** [comment]
:eyes: < `WebBundle生成時のプライマリURLの変更` これですかね？

**Comment by sasaplus1** [comment]
あ、なるほど、それが完了してないんですね。
