### ISSUE TITLE
達成基準のページに適合レベルの記載が無い

### ISSUE THREAD

**Issue by masuP9** [openameba/a11y-guidelines#150]
達成基準のページに適合レベルがあったほうがテストのときに便利

**Comment by itsminadesu** [comment]
💯 
<img width="842" alt="スクリーンショット 2022-06-13 10 11 19" src="https://user-images.githubusercontent.com/42470015/173264215-db9bf9a2-6249-415c-aa7b-83fb9a3e27d4.png">

**Comment by itsminadesu** [comment]
追記: 注釈のリンクのラベルを `こちら` から `適合レベルとは` に変更
