### ISSUE TITLE
画像のサイズ未指定で起こるレイアウトシフトの修正

### ISSUE THREAD

**Issue by herablog** [openameba/a11y-guidelines#151]
画像にサイズ指定がなくレイアウトシフトしています。このガイドラインの場合、事前にサイズが分かりそうなので付与しておくとよさそうです。

![thumbnail](https://user-images.githubusercontent.com/869023/104987800-dbbb3380-5a59-11eb-8597-f5cd7ba6d743.jpeg)
ロゴ画像にサイズ指定がなく、後続の要素がレイアウトシフトしている例。

**Comment by sasaplus1** [comment]
#181, #184
