### ISSUE TITLE
Github Actionsでtest,auditを実行する

### ISSUE THREAD

**Issue by tokimari** [openameba/a11y-guidelines#16]
元々の環境ではCircleCIを使っていたので、Github Actionsに移行します。
https://github.com/openameba/a11y-guidelines/blob/master/.circleci/config.yml この辺を移行します。

**Comment by sasaplus1** [comment]
why?

https://github.com/sasaplus1-prototype/lighthouse-ci-action-sandbox/actions

**Comment by sasaplus1** [comment]
lighthouse-ci-action and lhci are cannot access to httpd in github acion, but curl can. why???

https://github.com/sasaplus1-prototype/lighthouse-ci-action-sandbox/actions

**Comment by sasaplus1** [comment]
https://github.com/openameba/a11y-guidelines/pull/19#issuecomment-564820364

もやりたい

**Comment by tokimari** [comment]
https://github.com/openameba/a11y-guidelines/issues/16#issuecomment-562845796
@sasaplus1 さんと、そもそもauditsが公開されてるページでないと、Accessibility項くらいしかあんまり意味ないよね的な話をしました
push前にチェックするくらいでいいのかもなぁというお気持ち・・

**Comment by sasaplus1** [comment]
push直後にみるのはaccessibilityだけで良くて、デプロイされたものをcronでチェックするくらいでいいのかもしれないですね〜
