### ISSUE TITLE
[3.1.3]一般的でない用語は補足説明をする、に一般的でない用語の具体例が欲しい

### ISSUE THREAD

**Issue by masuP9** [openameba/a11y-guidelines#241]
「一般的でない用語」の定義が理解しにくいため、具体例を追加してほしいです。

例えば、以下のものが掲載できそうに思います。

- [達成基準 3.1.3 の事例](https://waic.jp/docs/UNDERSTANDING-WCAG20/meaning-idioms.html#meaning-idioms-examples-head)
- [Amebaヘルプ｜アメンバーってなに?](https://helps.ameba.jp/qguide/amember/post_186.html)

---

また、現在の説明だとUNDERSTANDINGにある「限定された用法で使われている単語」が認識から抜けそうかもです。「サービス独自の用語」に広く含まれるかもしれません。

> 一般的に使われていない用語やサービス独自の用語を使うと、ユーザーが内容を理解するのに時間がかかり、サービス側の意図した内容が十分に伝わらない可能性がある。

**Comment by tokimari** [comment]
@syasuda90 @itsminadesu 

> 現在の説明だとUNDERSTANDINGにある「限定された用法で使われている単語」が認識から抜けそうかもです。「サービス独自の用語」に広く含まれるかもしれません。
>> 一般的に使われていない用語やサービス独自の用語を使うと、ユーザーが内容を理解するのに時間がかかり、サービス側の意図した内容が十分に伝わらない可能性がある。

「限定された用法で使われている単語」が特に浮かばない・・・と思っていたんですが、もしかして「アメーバ」がそうかもしれない・・ 😇（社内だと当たり前すぎて気づけなかった・・）
ref: https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%A1%E3%83%BC%E3%83%90_(%E6%9B%96%E6%98%A7%E3%81%95%E5%9B%9E%E9%81%BF)
ガイドラインの説明としては、[概要セクション](https://a11y-guidelines.ameba.design/3/1/3/#%E6%A6%82%E8%A6%81)内に

> ### 例
> - アメーバ、Ameba：細胞の形態の１つを表す「アメーバ」ではなく、ネットサービスの名称として、サービス内で非常に限定された用法で使われている単語
> - アメンバー：Amebaブログで、特定記事を特定のユーザーのみに閲覧させるための機能で、サービス独自の用語
> - Ameba Pick：Amebaブログのアフィリエイト機能で、サービス独自の用語

みたいなのを追加するとイメージつきそうでしょうか。（アメーバの説明これでいいのだろうか）

**Comment by yasuda-shin** [comment]
候補としては「ブロガーズショップ」もありかなと思いつつ。

サービス用語として下記を見てみたんですが
https://github.com/openameba/textlint-rule-preset-ameba/blob/main/lib/prh-service.yml

- Ameba
- アメンバー
- Ameba Pick

でいいかもですね。
