### ISSUE TITLE
各項目の参考リンクがWCAG2.0解説書なので2.1に差し替える

### ISSUE THREAD

**Issue by syasuda90** [openameba/a11y-guidelines#253]
### 概要
WCAG2.1への翻訳がされていなかったため現時点では2.0達成方法集のリンクのままとしております。
必要に応じて2.1へのリンクに差し替えられればと。

https://github.com/openameba/a11y-guidelines/blob/master/src/1/4/4.md?plain=1#L108
想定されるWCAG2.1へのリンク（[G179](https://waic.jp/docs/WCAG21/Techniques/general/G179)）

https://github.com/openameba/a11y-guidelines/blob/master/src/3/2/1.md?plain=1#L36
想定されるWCAG2.1へのリンク（[G201](https://waic.jp/docs/WCAG21/Techniques/general/G201)）

**Comment by tokimari** [comment]
まだ全部出揃ってなさそう

**Comment by syasuda90** [comment]
残り2箇所のようです。
