### ISSUE TITLE
ガイドラインの各項のリンクを取得しやすくする

### ISSUE THREAD

**Issue by tokimari** [openameba/a11y-guidelines#257]
よくある、見出しにhover/focusするとリンクボタンが表示されて、ボタンをクリックすると該当の項のページ内リンクurlをコピーできる仕組みが欲しい。

ページ内の特定の具体例などをリンクすることが多いため、現状だとインスペクターを開いてidを確認してurlを作成する必要がありかなり面倒。

イメージ↓
![image](https://user-images.githubusercontent.com/4669600/138192868-5163ea87-ef71-46b1-aade-676416160e46.png)

**Comment by yasuda-shin** [comment]
https://github.com/openameba/a11y-guidelines/pull/271
👆で対応いただいたためissue closeします。
