### ISSUE TITLE
renovateのassigneesをランダムにする

### ISSUE THREAD

**Issue by sasaplus1** [openameba/a11y-guidelines#30]
renovateのPRのassigneeの指定を空にして、GitHub Actionsで renovateのPRがきたらassigneesをランダムで指定するのがいい気がしています。

assigneesに4,5人入っててもなあ……という気持ちです。

**Comment by tokimari** [comment]
大賛成です！！！ 🙌

**Comment by herablog** [comment]
おもしろい！

**Comment by sasaplus1** [comment]
https://github.com/openameba/a11y-guidelines/pull/35#issuecomment-568158689

**Comment by sasaplus1** [comment]
https://github.com/openameba/a11y-guidelines/pull/32#issuecomment-566819047 🤔
