### ISSUE TITLE
2.4.7 の良い実装例がフォーカス時のスタイルではない

### ISSUE THREAD

**Issue by masuP9** [openameba/a11y-guidelines#333]
[##良い実装例 2.4.7 フォーカスを見えるようにする - Ameba Accessibility Guidelines](https://a11y-guidelines.ameba.design/2/4/7/#%E8%89%AF%E3%81%84%E5%AE%9F%E8%A3%85%E4%BE%8B)

スタイルがフォーカス時ではなく、通常時のスタイルなので次のコードが良さそう。

```html
<style>
  .button1:focus-visible {
    outline: 1;
  }
  .button2:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px #fff, 0 0 0 4px #2d8c3c;
  }
</style>

<form>
  <label>ブラウザ標準の枠線を表示</label>
  <button class="button1">送信</button>

  <label>独自スタイルの枠線を表示</label>
  <button class="button2">送信</button>
</form>
```

**Comment by itsminadesu** [comment]
ご指摘いただきありがとうございます！
実装例を更新いたしました！ 🎉
<img width="365" alt="スクリーンショット 2022-06-14 18 14 07" src="https://user-images.githubusercontent.com/42470015/173541821-1208c5b4-c95c-4f83-a964-5facae9d99bb.png">
