### ISSUE TITLE
2.1.4 のタイトルが内容と不一致

### ISSUE THREAD

**Issue by masuP9** [openameba/a11y-guidelines#34]
2.1.4 のガイドラインが意味するところは、単一文字キーのショートカットを実装する場合、文字キーのショートカットをオフにする、リマップする、全体に適用しない、なので「文字キーのショートカットを操作できる」のタイトルでは内容と一致してないように思います。

主語が支援技術であれば、「（支援技術の）文字キーのショートカットを操作できる」となり内容と一致するので、主語をつけるか「文字キーのショートカットを解除、回避、限定できるようにする」とかが適切かと思います。

もっといいタイトルがあればディスカスしたい（そこは議論したい）

**Comment by tokimari** [comment]
ありがとうございます！確かに語弊がありますね。
〜〜を〜〜する（できる）形式で書いているのでちょっと修正いれつつ「文字キーのショートカットを解除、回避、限定できる」が良さそうに思います。

ただ、修飾キーと併用しているショートカットは問題ないので、「単一文字キーのショートカットを解除、回避、限定できる」がより正しそうですが、 `単一` を入れるかどうかについてはどう思われますか？？

**Comment by masuP9** [comment]
@tokimari 亀レスすみません。

> 単一文字キーのショートカットを解除、回避、限定できる

良さそう。PR出します。
