### ISSUE TITLE
1.3.5の実装例でplaceholderを使用しているのは、3.3.5と矛盾しているように見える

### ISSUE THREAD

**Issue by ymrl** [openameba/a11y-guidelines#385]
3.3.5では「悪い例」として、プレースホルダーに説明・記入例を記載することの問題点を指摘しています

>プレースホルダーのみに説明・入力例がある。これだと以下のような問題が起きやすい。
>
> - 入力中に読めない
> - プレースホルダーのテキストの色が薄すぎて読めない
>
> https://a11y-guidelines.ameba.design/3/3/5/

一方で、1.3.5の実装例では、記入例がplaceholder属性にセットされています

> ```html
> <label for="form-name">お名前</label>
> <input type="text" name="name" autocomplete="name" id="form-name" placeholder="山田 太郎">
> ```
>
> https://a11y-guidelines.ameba.design/1/3/5/

1.3.5の実装例となっている氏名・電話番号・住所などの入力項目は、3.3.5で想定されているような説明が必要な項目ではないように感じられますが、一方で、入力欄のプレースホルダーがどう扱われるべきものなのかがわかりにくい状況になっているようにも思えます。

**Comment by tokimari** [comment]
起票ありがとうございます！まさにまさにですね。
1.3.5の実装例を修正する方針で、修正検討いたします！:pray:
