### ISSUE TITLE
1.4.3 「大きな文字」の基準を日本語の全角文字基準にする

### ISSUE THREAD

**Issue by tokimari** [openameba/a11y-guidelines#433]
### 概要 / Overview

[1.4.3 テキストや文字画像のコントラストを確保する](https://a11y-guidelines.ameba.design/1/4/3/)の「大きな文字」の基準が英語圏相当のサイズになっています。Amebaは日本語圏を主なターゲットにしているので、日本語の全角文字基準のサイズにするのが適切そうです。

### before

```
ここで、「大きな文字」とは以下の通り。
- 18.5px以上の太字（14pt相当）
- 24px以上（18pt相当）
```

### after

```
ここで、「大きな文字」とは以下の通り。（Amebaでは主に日本語が用いられているため、日本語の全角文字の場合の基準値を用いている[^1]）
- 24px以上の太字（18pt相当）
- 29px以上（22pt相当）

[^1]: [達成基準 1.4.3: コントラスト (最低限)を理解する](https://waic.jp/translations/WCAG21/Understanding/contrast-minimum.html)の「サイズの大きな (テキスト) (large scale (text))」の訳注参照
```

## 参考情報

他社では、freeeさんのガイドラインで日本語相当のサイズを採用しているようです。
https://a11y-guidelines.freee.co.jp/categories/text.html#gl-text-contrast

### 関連リンク / Related link

https://a11y-guidelines.ameba.design/1/4/3/

### その他 / Others

画像や動画中の文字サイズについては、表示端末幅に依存するため、どのようにルール化すべきか別途検討予定です

**Comment by tokimari** [comment]
デザイナーさん確認（ @MasatoHonda 、こなちゃん）okです 👌

**Comment by yossydev** [comment]
@tokimari 
お疲れ様です！こちら自分が対応させていただきます！！
そちらにあたって一点質問です！！

```
[^1]: [達成基準 1.4.3: コントラスト (最低限)を理解する](https://waic.jp/translations/WCAG21/Understanding/contrast-minimum.html)の「サイズの大きな (テキスト) (large scale (text))」の訳注参照
```

<img width="743" alt="image" src="https://github.com/openameba/a11y-guidelines/assets/87469023/663e5e3a-d513-42d2-b47c-4dac1df1c329">

↑ こちらはこのようなUIになる認識であっていますでしょうか?? :eyes:
