### ISSUE TITLE
[1.4.3] tota11yのリンク切れ

### ISSUE THREAD

**Issue by te19oishi** [openameba/a11y-guidelines#487]
### 概要 / Overview

以下のセクションのtota11yのリンクが切れており、Chrome拡張機能も非推奨になっています。
[実装時](https://a11y-guidelines.ameba.design/1/4/3/#%E5%AE%9F%E8%A3%85%E6%99%82)
[tota11y(リンク切れ)](https://khan.github.io/tota11y/)
[Chrome Extension(非推奨)](https://chrome.google.com/webstore/detail/oedofneiplgibimfkccchnimiadcmhpe)

### 対応
以下の2パターン考えられるかと思います。
1. 削除
2. 代替

#### 1. 削除 の場合
以下の部分を削除するだけ
```
また tota11y というツールを使うことでもチェックできる。tota11yは、Chrome Extension としても入手できる。
```

#### 2. 代替 の場合
tota11yの[README](https://github.com/jdan/tota11y?tab=readme-ov-file#tota11y-)に記載のあるツールに置き換える。
- [axe](https://www.deque.com/axe)
- [Chrome Extension](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd)

あえてaxeを載せる必要がなければ削除で良い気はしますが、どうしましょうか？

**Comment by tokimari** [comment]
ありがとうございます！とても助かります！
チェック方法はアップデートしたいねと話していたので、 https://github.com/openameba/a11y-guidelines/issues/386 一旦削除のみ先にしようかなと思います！ 🙏

**Comment by te19oishi** [comment]
@tokimari 
一応PR作ったのですが不要でしたかね？🤔
チェック方法のアップデートのような別の機会に一緒にするとかであればクローズしちゃっても大丈夫ですが！
#488

**Comment by tokimari** [comment]
神様ですか・・！！！？ 😭 ❤️ ありがとうございます！

**Comment by tokimari** [comment]
close by https://github.com/openameba/a11y-guidelines/pull/488
