### ISSUE TITLE
チェックリストを作成する

### ISSUE THREAD

**Issue by tokimari** [openameba/a11y-guidelines#5]
（ここでやるかはわからない）

ガイドラインベースだと、網羅的＋難易度の高いものも多分に含まれている
具体的に何に気をつけるべきなのかの一覧性が低い

チェックリスト形式で、ガイドラインを参照する一覧を作成したい。

ほしいもの
- 職種ごとでフィルターしたい
- 適合レベル（A/AA/AAA）のフィルター

**Comment by yasuda-shin** [comment]
すでに組織内にあり利用されているためこちらcloseさせていただきます。
