### ISSUE TITLE
1.1.1 アイコンの実装例の再考

### ISSUE THREAD

**Issue by tokimari** [openameba/a11y-guidelines#56]
https://openameba.github.io/a11y-guidelines/1/1/1/

WAI-ARIA 1.2 で generic role に対して `aria-label` の付与は禁止されています。（@masuP9 さんより）

つまり https://openameba.github.io/a11y-guidelines/1/1/1/#ラベルのないアイコンに、代替テキストを設定する の良い実装例はむしろ悪い実装例であったことになります。

そのため、推奨する実装例を下記の代替案のように変更しようと思います。
ただしWebに限った話であること、長くなりすぎることから、推奨例以外はaccordionなどで隠しても良いかもと思っています。

※慣例的にアイコンに `i` 要素を使うことが多いですが、i要素自体はアイコンのために使うものではなく、誤解を招く恐れもあることから`span`要素とします。

### 推奨
不可視のテキスト要素を用意し、アイコン自体は支援技術に無視させる方法。

```
<button>
    <span class="icon-close" aria-hidden="true"></span>
    <span class="visually-hidden">閉じる</span>
</button>
```

### ok1
親要素にラベルを設定する方法。
`visually-hidden` クラスの使用が難しい場合（？）や実装上の都合でアイコン用のDOMに付与が難しい場合など
```
<button aria-label="閉じる">
    <span class="icon-close" aria-hidden="true"></span>
</button>
```

### ok2

roleを`generic`ではなく`img`にした上で、`aria-label`を付与する方法。
```
<button>
    <span class="icon-close" role="img" aria-label="閉じる"></span>
</button>
```

**Comment by masuP9** [comment]
visually-hidden を推奨する理由とかいるかな？

- 機械翻訳されやすい
- 対応している支援技術が多い

**Comment by tokimari** [comment]
たしかに:eyes:入れましょう。
あと `visually-hidden` とは（なにこれ＆Amebaではどう書くの）の解説いるのかなと考えたらいくらでも長くなる・・:innocent:
用語集が必要かな・・

**Comment by masuP9** [comment]
あとはウェブの実装だからなーとかいうのもある。プラットフォーム固定というか

**Comment by tokimari** [comment]
そうなんですよね。。
アプリはアプリで事例集入れたいと思ってますが、結構先にはなりそう 😇
