### ISSUE TITLE
このガイドラインのライセンス

### ISSUE THREAD

**Issue by ymrl** [openameba/a11y-guidelines#73]
こんにちは。
弊社 (freee) でもこちらのガイドラインも参考にしつつ、アクセシビリティガイドラインの整備をしていているんですが、ガイドラインのドキュメントを公開するにあたって、Amebaさんのガイドラインではライセンスが明示されていないことに気付きました。
著作権表記はあるのですが、ライセンスが明示されているほうが良いのかなと思います。

弊社では、ガイドラインはCC BY 4.0にて予定で、検討過程ではMITやBSDライセンスも候補となっていました。

**Comment by masuP9** [comment]
@ymrl こんにちはこんにちは。

たしかにライセンス明示してなかったですね。ありがとうございます。早速検討しています。

ちなみにMITやBSDライセンスではなくてCC BY 4.0にした理由はどのようなものでしょう？差し支えなければおしえてください。

**Comment by ymrl** [comment]
> ちなみにMITやBSDライセンスではなくてCC BY 4.0にした理由はどのようなものでしょう？差し支えなければおしえてください。

特に理由はなくて、ガイドラインはソフトウェアではなく文書なので、MITやBSDのようにソフトウェアを前提としているものよりは適しているだろうくらいのものです。
ライセンスを明示することで、社外の人でも安心して参考にしたり改変して独自のガイドラインを作れたりするようにするのが目的だったので、強いこだわりがあったわけでもないんですよね

**Comment by masuP9** [comment]
たしかにかーにです。ありがとうございます！

**Comment by tokimari** [comment]
@ymrl さん起票ありがとうございました！
遅くなりましたがライセンス表記追加しましたー！:pray:
