### ISSUE TITLE
404ページがGitHubページのものになっている

### ISSUE THREAD

**Issue by yamanoku** [openameba/a11y-guidelines#81]
こちらのガイドラインを参考にしている者です。
達成基準の項目通りにURLを入力できるのはとても便利（たとえば2.4.1なら `/a11y-guidelines/2/4/1/`と打つ）ですが、
間違って、ない項目を入力した時にGitHubページの404ページに移動してしまいました。

<img width="701" alt="GitHubページの404ページのスクリーンショット" src="https://user-images.githubusercontent.com/1996642/83018386-2cf85c00-a060-11ea-939a-d4879c35e8b8.png">

こちら、ガイドラインのトップページに戻るなどの独自の404ページがあると安心かなと思いました。
ガイドラインそのものとしてのIssueではなくWebページとしての機能についてですが考慮頂けますと 🙏

**Comment by tokimari** [comment]
起票ありがとうございます！助かります 😊
