### ISSUE TITLE
og:imageが404

### ISSUE THREAD

**Issue by hrfmmymt** [openameba/a11y-guidelines#92]
です！

> `<meta property=og:image content=https://openameba.github.io/a11y-guidelines/favicon.png>`

**Comment by hrfmmymt** [comment]
元々がなんだったか…

https://openameba.github.io/a11y-guidelines/img/logo.svg こりとかですかね？

**Comment by syasuda90** [comment]
svgどーでしたっけ。
できればpngかjpgの方がいいと思いますしlogo.svgだと伝わらないような...
Ameba Accessibility Guidelinesのog:imageちゃんと作った方がよい気がします。
