### ISSUE TITLE
ソースコードのライセンスについて

### ISSUE THREAD

**Issue by tsmd** [openameba/a11y-guidelines#99]
本リポジトリ上にあるソースコードのライセンスはどれが適切でしょうか？

- MIT
- CC BY 4.0
- All rights reserved

[ウェブ上で公開されているガイドライン](https://openameba.github.io/a11y-guidelines/)のライセンスは CC BY 4.0 である旨が記載されていますが、ウェブサイトからアクセスできるリソースに関するライセンスであろうと思われました。一方で、本リポジトリのソースコードのライセンスは特に明示されていないようでした。

…いえ、よく見たら package.json のなかに `"license": "mit"` の記述がありました。本リポジトリのコードは MIT でしょうか？

弊社でもアクセシビリティガイドラインを策定するにあたって、ぜひ Ameba のガイドラインを下地にして作りたいと思っており、ライセンスについて明確なところをしりたくなったという経緯でご質問させていただいています。🙇‍♂️

**Comment by masuP9** [comment]
@tsmd 

> 弊社でもアクセシビリティガイドラインを策定するにあたって、ぜひ Ameba のガイドラインを下地にして作りたい

とっても嬉しいです。ぜひ！

## 回答

リポジトリ内で表記しているライセンスについて回答します。基本的にはガイドライン本文もソースコードに関しても自由に使っていただきたいと考えています。

###  All rights reserved

著作権は株式会社サイバーエージェントが保有する、以上の意味はないのですが、そもそもあまり意味のない表記ですね。著作権表示をシンプルにできないか検討してみます。

### CC BY 4.0

> ウェブサイトからアクセスできるリソースに関するライセンスであろうと思われました

この認識であってます。CC BY 4.0 を選択したのは最終的なアウトプットがソフトウェアではないためです。経緯は[feat: ライセンス表記を追加 by tokimari · Pull Request \#83 · openameba/a11y\-guidelines](https://github.com/openameba/a11y-guidelines/pull/83) をご参考ください。

### MIT

FRESH LIVEのガイドラインのライセンスがMITだったので、そのまま残ってしまった可能性があります。

とはいえソースコードも自由に使っていただけるよう、MITで提供したいと考えているのですが、ソースコードに含まれるロゴなどのブランドアセットに関しての取り扱いが不明でMITで公開できるか検討中です。よって `package.json` に `license: "mit"` 表記があるのは問題かもしれません。こちらも対応を検討します。

**Comment by masuP9** [comment]
@tsmd 本リポジトリのコンテンツのライセンスを以下の通りとしました 💪 

```
# LICENSE

## Guidelines

CC BY 4.0

## Program for build guidelines

MIT

## Ameba logos and other brand assets

No License
```

**Comment by tsmd** [comment]
@masuP9 承知しました。
ありがとうございます！！
